#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

awk \
  '
    BEGIN {
      FS = ":.*? ## "
    }

    NF == 2 {
      printf("\033[36m%-16s\033[0m %s\n", $1, $2)
    }
  ' \
  Makefile
