#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

date=$(date -u +"%Y-%m-%d")

tempdir=$(mktemp -d)
trap "rm -Rf '${tempdir}'" EXIT

updated_changelog="${tempdir}/CHANGELOG.md"
release_notes="${tempdir}/${VERSION}.md"

awk \
  -v date="${date}" \
  -v no_changes="No notable changes." \
  -v release_notes="${release_notes}" \
  -v updated_changelog="${updated_changelog}" \
  -v version="${VERSION}" \
  '
    $0 == "## [Unreleased]" {
      in_release_notes=1

      printf("%s\n\n%s\n\n\n## [%s] - %s\n", $0, no_changes, version, date) > updated_changelog

      next
    }

    $1 == "[Unreleased]:" {
      in_release_notes=0

      tag=sprintf("v%s", version)

      compare_unreleased=$2
      sub(/[^\/]+\.\.\./, sprintf("%s...", tag), compare_unreleased)
      printf("%s %s\n", $1, compare_unreleased) > updated_changelog

      compare_released=$2
      sub(/HEAD/, tag, compare_released)
      printf("[%s]: %s\n", version, compare_released) > updated_changelog

      next
    }

    {
      if ($1 == "##") {
        in_release_notes=0
      }

      if (in_release_notes) {
        if ($0 == no_changes) {
          print("Aborting: no unreleased changes found in changelog") > "/dev/stderr"
          exit(1)
        }

        print($0) > release_notes
      }

      print($0) > updated_changelog
    }
  ' \
  CHANGELOG.md

mv "${updated_changelog}" CHANGELOG.md

cat "${release_notes}"
